myRailApp/config/routes.rb
#routers to do crud action with database
Rails.application.routes.draw do
  resources :covids, only: :writedata
  get 'covid/index', to: 'covid#index'
  post 'covid/create', to: 'covid#create'
  get 'covid/show', to: 'covid#show'
  patch '/covid/update' => 'covid#update'
  get 'covid/edit', to: 'covid#edit'
  delete 'covid/delete', to: 'covid#delete'
  get 'covid/new', to: 'covid#new'
  get 'covid/writedata' => 'covid#writedata'
  post 'covid/import' => 'covid#import'
  # end
root to: 'covid#index'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

  # get 'covid/index'
  # resources :covid do
    # put '/update/:id', to: 'covid#update', :as => :update_recall
    # put '/delete/:id', to: 'covid#delete', :as => :delete_recall
  # collection {post :import}
  # end

myRailApp/app/models/covid.rb
#  Author: Shuting Yang
#  Date September 24, 2019
#  Description: Covid object for covid records.
 
require "time"
# Represents a covid-19 statictis record from a csv file 
# @author Shuting Yang
class Covid < ApplicationRecord
    require 'csv'
    
    # transform all data to csv
    def self.to_csv
        attributes = %w{cid date cases deaths name_en name_fr}
    
        CSV.generate(headers: true) do |csv|
            csv << attributes
        
            all.each do |user|
                csv << attributes.map{ |attr| user.send(attr) }
            end
        end
    end
    

    # If string is not null return it,
    # Strings with only "null" or blank result in null reference being returned.
    # @param [String] String to be processed
    # @return [String] processed String or null
    def self.processAsString(value)
        if value.nil? || value.blank?
          nil
        else 
          value
        end
    end

    #  Utility method that cleans the String passed and attempts to convert
    #  it into an Integer. If the passed String is null, empty, or contains "null",
    #  then a null is returned.
    #  @param [String] String to be processed
    #  @return [Integer] Integer or null
    def self.processAsInteger(value) 
        result = processAsString(value);
        result==nil ? nil: Integer(result);
    end
    
    #  Utility method that cleans the String passed and attempts to convert
    #  it into a Date. If the passed String is null, empty, or contains "null",
    #  then a null is returned.
    #  @param [String] String to be processed
    #  @return [Date] or null 
    def self.processAsLocalDate(value)
        result = processAsString(value);
        result==nil ? nil: Date.parse(result);
    end

    # basic string reprentation of the covid data record */
    def to_s
        '%s %s %s %s %s %s' % [@cid, @date, @cases, @deaths, @name_en, @name_fr]
    end
end

    # attr_accessible :id, :date, :cases, :deaths, :cases_100k, :cases_14_100k, :name_fr, :name_en

    # Default Constructor */
    # String-based constructor, to facilitate reading string values from csv file.
    # The strings are cleaned, and converted to the appropriate type where needed, 
    # additionally empty strings are converted to null references.
    # def initialize(params)    
    #     super()
    #     params ||={}
    #     @id = processAsString(params[:id])
    #     @date = processAsLocalDate(params[:date])
    #     @cases = processAsInteger(params[:cases])
    #     @deaths = processAsInteger(params[:deaths])
    #     @name_fr = processAsString(params[:name_fr])
    #     @name_en = processAsString(params[:name_en])
    # end

myRailApp/app/controllers/covid_controller.rb
#  Author: Shuting Yang
#  Date: Sep 20, 2020
#  Modified Sep 24, 2020
#  Description: Sample program, that uses Rails CSV library to open
#  and print records from the CSV dataset on screen.
 
#  csv data retrieve from government site https://open.canada.ca/data/en/dataset/fc11aa70-821b-4c64-be19-020a2465b0de
#  License is from government site https://open.canada.ca/en/open-government-licence-canada
#   as well as included in this project folder.
require 'csv'
class CovidController < ApplicationController
  # read all data
  def index
    # import_from_csv()
    @covids = Covid.all
  end

  # create new record object
  def new
    @covidRecord = Covid.new
    render :new
  end

  # create new record object and insert to db
  def create
    @covids = Covid.create(covid_params)
    redirect_to '/'
  end

  # edit the object redirect to edit form
  def edit 
    @crecord = Covid.find(params[:id])
    respond_to do |format|
      format.html { render :edit, locals: { crecord: @crecord } }
    end
  end

  # find record and show detail
  def show
    @crecord = Covid.find(params[:id])
    render :show
  end

  # update record detail
  def update  
    @record = Covid.find(params[:id])
    # @record.update(cid: params[:cid], date: params[:date], deaths: params[:deaths], cases: param[:cases], name_fr: param[:name_fr], name_en: param[:name_en])
    # redirect_to covid_index_path
    # respond_to do |format|
    if @record.update(covid_params)
      redirect_to '/'
    else
      render :edit
    end
  end

  # delete record object 
  def delete 
    @record = Covid.find(params[:id])
    @record.destroy!
    redirect_to '/'
  end

  # import data set from csv
  def import
    import_from_csv
    redirect_to '/'
  end

  # write data to another csv
  def writedata
    @records = Covid.all
    respond_to do |format|
      format.html
      format.csv { send_data @records.to_csv, filename: "users-#{Date.today}.csv" }
    end
  end
  
  # use for initial new record obj
  private
    def covid_params
      # It's mandatory to specify the nested attributes that should be permitted.
      # If you use `permit` with just the key that points to the nested attributes hash,
      # it will return an empty hash.
      params.require(:covid).permit(:cid, :date, :cases, :deaths, :name_fr, :name_en )
    end

  # program by Shuting Yang
  # open csv file
  def openFile
    begin
        csv = File.path('/Users/shutingyang/Desktop/CST8333ruby/myRailApp/app/controllers/InternationalCovid19Cases.csv')
    rescue SystemCallError => e
        puts e.class # => Errno::ENOENT
        puts e.class.superclass # => SystemCallError
        puts e.class.superclass.superclass # => StandardError
    end
  end
  
  # program by Shuting Yang
  # import data from csv
  def import_from_csv
    Covid.delete_all
    csv = openFile()
    i=0
    CSV.foreach(csv, headers: true) do |row|
        row_hash = row.to_h
        object = Covid.create!(              
            cid: Covid.processAsString(row_hash['id']),
            date: Covid.processAsLocalDate(row_hash['date']),
            cases: Covid.processAsInteger(row_hash['cases']),
            deaths: Covid.processAsInteger(row_hash['deaths']),
            name_fr: Covid.processAsString(row_hash['name_fr']),
            name_en: Covid.processAsString(row_hash['name_en']) )
        i+=1;
        break if i>=100;
    end
  end

  # take a list of covid data object, loop through it and print out them
  # param [array]
  def printList(list)
    list.each do |item|
      puts item
    end
  end

end

myRailApp/app/helpers/covid_helper.rb
module CovidHelper
end

myRailApp/app/views/covid/edit.html.erb
<h1>Program by Shuting Yang</h1>
<h1>Update covid record form</h1>
<%= form_for @crecord, url: covid_update_path(:id=>@crecord.id), method: :patch do |f| %>
  <% if @crecord %>
  
    <span>label</span><br>
    <%= f.text_field :cid =%><br>

    <span>date</span><br>
    <%= f.text_field :date =%><br>

    <span>cases</span><br>
    <%= f.text_field :cases =%><br>

    <span>deaths</span><br>
    <%= f.text_field :deaths =%><br>

    <span>name_fr</span><br>
    <%= f.text_field :name_fr =%><br>

    <span>name_en</span><br>
    <%= f.text_field :name_en =%><br>

    <%= f.submit "Submit" %>
  <% end %>
<% end %>

myRailApp/app/views/covid/index.html.erb
<h1>Program by Shuting Yang</h1>
<%= flash[:notice] =%>
    <%= link_to "<button>load data</button>".html_safe, covid_import_path(), method: :post %>
    <%= link_to 'create new record', covid_new_path() %>
    <%= link_to 'write to csv', covid_writedata_path(format: "csv") %>
<table id="datatable">
    <thead>
        <tr>
            <th>db_id</th>
            <th>record_id</th>
            <th>date</th>
            <th>cases</th>
            <th>deaths</th>
            <th>name_fr</th>
            <th>name_en</th>
            <th> show action</th>
            <th> update action</th>
            <th> delete action</th>
        </tr>
    </thead>
    <tbody>
        <% @covids.each do |covid| %>
        <tr>
            <td><%= covid.id =%></td>
            <td><%= covid.cid =%></td>
            <td><%= covid.date=%></td>
            <td><%= covid.cases=%></td>
            <td><%= covid.deaths=%></td>
            <td><%= covid.name_fr=%></td>
            <td><%= covid.name_en=%></td>
            <td><%= link_to 'Show detail', covid_show_path(:id => covid.id) %></td>
            <td><%= link_to 'Edit', covid_edit_path(:id => covid.id), method: :get%></td>
            <td><%= link_to 'Delete', covid_delete_path(:id => covid.id),method: :delete, data: {confirm: "Are you sure"} %></td>
        </tr>
        <% end %>
    </tbody>
</table>

myRailApp/app/views/covid/new.html.erb
<h1>Program by Shuting Yang</h1>
<h1>Insert covid record form</h1>
<%= form_for @covidRecord, url: covid_create_path(@covidRecord), method: :post do |f| %>
  <% if @covidRecord %>
    <span>label</span><br>
    <%= f.text_field :cid =%><br>

    <span>date</span><br>
    <%= f.text_field :date =%><br>

    <span>cases</span><br>
    <%= f.text_field :cases =%><br>

    <span>deaths</span><br>
    <%= f.text_field :deaths =%><br>

    <span>name_fr</span><br>
    <%= f.text_field :name_fr =%><br>

    <span>name_en</span><br>
    <%= f.text_field :name_en =%><br>

    <%= f.submit "Submit" %>
  <% end %>
<% end %>

myRailApp/app/views/covid/show.html.erb
<h1>Program by Shuting Yang</h1>
<% if @crecord %>
    <ul>
        <li><%= @crecord.id =%></li>
        <li><%= @crecord.cid =%></li>
        <li><%= @crecord.date =%></li>
        <li><%= @crecord.cases =%></li>
        <li><%= @crecord.deaths=%></li>
        <li><%= @crecord.name_fr =%></li>
        <li><%= @crecord.name_en =%></li>
    </ul>
<% end %>